"""supervisor controls and versioned rubrics"""

from alembic import op
import sqlalchemy as sa
import uuid

LEGACY_ID = "00000000-0000-0000-0000-000000000001"
LEGACY = [
    {
        "key": "greeting",
        "label": "Greeting",
        "max_score": 10,
        "criteria": "Welcomes the caller and identifies the dispatcher or company.",
    },
    {
        "key": "professionalism",
        "label": "Professionalism",
        "max_score": 20,
        "criteria": "Uses respectful language, empathy, and ownership. Do not infer vocal tone from text.",
    },
    {
        "key": "information_gathering",
        "label": "Information Gathering",
        "max_score": 20,
        "criteria": "Confirms relevant delivery details, caller needs, and identifiers.",
    },
    {
        "key": "communication",
        "label": "Communication",
        "max_score": 20,
        "criteria": "Provides clear, understandable information and confirms understanding.",
    },
    {
        "key": "resolution",
        "label": "Resolution",
        "max_score": 20,
        "criteria": "Offers a concrete next step, realistic expectation, and ownership of follow-up.",
    },
    {
        "key": "closing",
        "label": "Closing",
        "max_score": 10,
        "criteria": "Summarizes next steps, offers further help, and closes courteously.",
    },
]

revision = "c301d927fb02"
down_revision = "b192cb82ae01"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rubrics",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("version", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("activated_at", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    with op.batch_alter_table("rubrics", schema=None) as batch_op:
        batch_op.create_index(
            "one_active_rubric",
            ["status"],
            unique=True,
            sqlite_where=sa.text("status = 'ACTIVE'"),
            postgresql_where=sa.text("status = 'ACTIVE'"),
        )

    op.add_column("calls", sa.Column("requested_rubric_id", sa.String(36), nullable=True))

    op.create_table(
        "rubric_categories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("rubric_id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("criteria", sa.Text(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["rubric_id"], ["rubrics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rubric_categories", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rubric_categories_rubric_id"), ["rubric_id"], unique=False)

    op.create_table(
        "speaker_corrections",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("call_id", sa.String(length=36), nullable=False),
        sa.Column("source_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("source_start", sa.Integer(), nullable=False),
        sa.Column("source_end", sa.Integer(), nullable=False),
        sa.Column("speaker_id", sa.Text(), nullable=True),
        sa.Column("inferred_role", sa.String(length=20), nullable=False),
        sa.Column("previous_role", sa.String(length=20), nullable=False),
        sa.Column("corrected_role", sa.String(length=20), nullable=True),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("corrected_by", sa.String(length=36), nullable=False),
        sa.Column("corrected_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["call_id"],
            ["calls.id"],
        ),
        sa.ForeignKeyConstraint(
            ["corrected_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("speaker_corrections", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_speaker_corrections_call_id"), ["call_id"], unique=False)

    # Seed a frozen copy of v1, never import mutable application criteria here.
    conn = op.get_bind()
    conn.execute(
        sa.text(
            "INSERT INTO rubrics (id,name,version,status,revision,created_at,activated_at) VALUES (:id,'Dispatch QA','1.0','ACTIVE',1,0,0)"
        ),
        {"id": LEGACY_ID},
    )
    for i, c in enumerate(LEGACY):
        conn.execute(
            sa.text(
                "INSERT INTO rubric_categories (id,rubric_id,key,name,description,weight,criteria,display_order) VALUES (:id,:rubric_id,:key,:name,'',:weight,:criteria,:position)"
            ),
            dict(
                id=str(uuid.uuid4()),
                rubric_id=LEGACY_ID,
                key=c["key"],
                name=c["label"],
                weight=c["max_score"],
                criteria=c["criteria"],
                position=i,
            ),
        )
    op.add_column("qa_evaluations", sa.Column("id", sa.String(36), nullable=True))
    op.add_column("qa_evaluations", sa.Column("rubric_id", sa.String(36), nullable=True))
    conn.execute(
        sa.text("UPDATE qa_evaluations SET id=call_id, rubric_id=:id WHERE rubric_version='1.0'"), {"id": LEGACY_ID}
    )
    conn.execute(sa.text("UPDATE qa_evaluations SET id=call_id WHERE id IS NULL"))
    with op.batch_alter_table("qa_evaluations", naming_convention={"pk": "pk_%(table_name)s"}) as batch_op:
        batch_op.drop_constraint("pk_qa_evaluations", type_="primary")
        batch_op.alter_column("id", existing_type=sa.String(36), nullable=False)
        batch_op.create_primary_key("pk_qa_evaluations", ["id"])
        batch_op.add_column(sa.Column("reviewed_by", sa.String(36), nullable=True))
        batch_op.add_column(sa.Column("reviewed_at", sa.Float(), nullable=True))
        batch_op.create_index("ix_qa_evaluations_call_id", ["call_id"], unique=False)
        batch_op.create_foreign_key("fk_evaluation_reviewer", "users", ["reviewed_by"], ["id"])
        batch_op.create_foreign_key("fk_evaluation_rubric", "rubrics", ["rubric_id"], ["id"])

    op.create_table(
        "score_adjustments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("evaluation_id", sa.String(length=36), nullable=False),
        sa.Column("category_key", sa.String(length=80), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("previous_score", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("changed_by", sa.String(length=36), nullable=False),
        sa.Column("changed_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["qa_evaluations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("score_adjustments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_score_adjustments_evaluation_id"), ["evaluation_id"], unique=False)


def downgrade():
    conn = op.get_bind()
    if conn.execute(sa.text("SELECT call_id FROM qa_evaluations GROUP BY call_id HAVING count(*) > 1")).first():
        raise RuntimeError("Cannot downgrade while evaluation history exists; restore a backup instead")
    if (
        conn.execute(sa.text("SELECT id FROM score_adjustments LIMIT 1")).first()
        or conn.execute(sa.text("SELECT id FROM speaker_corrections LIMIT 1")).first()
    ):
        raise RuntimeError("Cannot downgrade while supervisor audit records exist; restore a backup instead")
    op.drop_table("score_adjustments")
    op.drop_table("speaker_corrections")
    with op.batch_alter_table("qa_evaluations") as batch_op:
        batch_op.drop_constraint("fk_evaluation_reviewer", type_="foreignkey")
        batch_op.drop_constraint("fk_evaluation_rubric", type_="foreignkey")
        batch_op.drop_constraint("pk_qa_evaluations", type_="primary")
        batch_op.drop_index("ix_qa_evaluations_call_id")
        batch_op.drop_column("reviewed_at")
        batch_op.drop_column("reviewed_by")
        batch_op.drop_column("rubric_id")
        batch_op.drop_column("id")
        batch_op.create_primary_key("pk_qa_evaluations", ["call_id"])
    op.drop_column("calls", "requested_rubric_id")
    op.drop_table("rubric_categories")
    op.drop_table("rubrics")
